
  export const CATALOGPRODUCTS_RECEIVED = "CATALOGPRODUCTS_RECEIVED";
  export const SET_CATALOGPRODUCT = "SET_CATALOGPRODUCT";
  export const CREATE_CATALOGPRODUCT = "CREATE_CATALOGPRODUCT";
  export const SET_PROPERTY_CATALOGPRODUCT = "SET_PROPERTY_CATALOGPRODUCT";
  