export const states = [
  {
    name: "Aguascalientes",
    code_2_digits: "AG",
    code_3_digits: "AGS",
    code_shopify: "AGS",
    country_code: "MX",
  },
  {
    name: "Baja California",
    code_2_digits: "BC",
    code_3_digits: "BCN",
    code_shopify: "BC",
    country_code: "MX",
  },
  {
    name: "Baja California Sur",
    code_2_digits: "BS",
    code_3_digits: "BCS",
    code_shopify: "BCS",
    country_code: "MX",
  },
  {
    name: "Campeche",
    code_2_digits: "CM",
    code_3_digits: "CAM",
    code_shopify: "CAMP",
    country_code: "MX",
  },
  {
    name: "Chiapas",
    code_2_digits: "CS",
    code_3_digits: "CHP",
    code_shopify: "CHIS",
    country_code: "MX",
  },
  {
    name: "Chihuahua",
    code_2_digits: "CH",
    code_3_digits: "CHH",
    code_shopify: "CHIH",
    country_code: "MX",
  },
  {
    name: "Ciudad de México",
    code_2_digits: "CX",
    code_3_digits: "CMX",
    code_shopify: "DF",
    country_code: "MX",
  },
  {
    name: "Coahuila",
    code_2_digits: "CO",
    code_3_digits: "COA",
    code_shopify: "COAH",
    country_code: "MX",
  },
  {
    name: "Colima",
    code_2_digits: "CL",
    code_3_digits: "COL",
    code_shopify: "COL",
    country_code: "MX",
  },
  {
    name: "Durango",
    code_2_digits: "DG",
    code_3_digits: "DGO",
    code_shopify: "DGO",
    country_code: "MX",
  },
  {
    name: "Guanajuato",
    code_2_digits: "GT",
    code_3_digits: "GTO",
    code_shopify: "GTO",
    country_code: "MX",
  },
  {
    name: "Guerrero",
    code_2_digits: "GR",
    code_3_digits: "GRO",
    code_shopify: "GRO",
    country_code: "MX",
  },
  {
    name: "Hidalgo",
    code_2_digits: "HG",
    code_3_digits: "HGO",
    code_shopify: "HGO",
    country_code: "MX",
  },
  {
    name: "Jalisco",
    code_2_digits: "JA",
    code_3_digits: "JAL",
    code_shopify: "JAL",
    country_code: "MX",
  },
  {
    name: "México",
    code_2_digits: "EM",
    code_3_digits: "MEX",
    code_shopify: "MEX",
    country_code: "MX",
  },
  {
    name: "Michoacán",
    code_2_digits: "MI",
    code_3_digits: "MIC",
    code_shopify: "MICH",
    country_code: "MX",
  },
  {
    name: "Morelos",
    code_2_digits: "MO",
    code_3_digits: "MOR",
    code_shopify: "MOR",
    country_code: "MX",
  },
  {
    name: "Nayarit",
    code_2_digits: "NA",
    code_3_digits: "NAY",
    code_shopify: "NAY",
    country_code: "MX",
  },
  {
    name: "Nuevo León",
    code_2_digits: "NL",
    code_3_digits: "NLE",
    code_shopify: "NL",
    country_code: "MX",
  },
  {
    name: "Oaxaca",
    code_2_digits: "OA",
    code_3_digits: "OAX",
    code_shopify: "OAX",
    country_code: "MX",
  },
  {
    name: "Puebla",
    code_2_digits: "PU",
    code_3_digits: "PUE",
    code_shopify: "PUE",
    country_code: "MX",
  },
  {
    name: "Querétaro",
    code_2_digits: "QT",
    code_3_digits: "QRO",
    code_shopify: "QRO",
    country_code: "MX",
  },
  {
    name: "Quintana Roo",
    code_2_digits: "QR",
    code_3_digits: "ROO",
    code_shopify: "Q ROO",
    country_code: "MX",
  },
  {
    name: "San Luis Potosí",
    code_2_digits: "SL",
    code_3_digits: "SLP",
    code_shopify: "SLP",
    country_code: "MX",
  },
  {
    name: "Sinaloa",
    code_2_digits: "SI",
    code_3_digits: "SIN",
    code_shopify: "SIN",
    country_code: "MX",
  },
  {
    name: "Sonora",
    code_2_digits: "SO",
    code_3_digits: "SON",
    code_shopify: "SON",
    country_code: "MX",
  },
  {
    name: "Tabasco",
    code_2_digits: "TB",
    code_3_digits: "TAB",
    code_shopify: "TAB",
    country_code: "MX",
  },
  {
    name: "Tamaulipas",
    code_2_digits: "TM",
    code_3_digits: "TAM",
    code_shopify: "TAMPS",
    country_code: "MX",
  },
  {
    name: "Tlaxcala",
    code_2_digits: "TL",
    code_3_digits: "TLA",
    code_shopify: "TLAX",
    country_code: "MX",
  },
  {
    name: "Veracruz",
    code_2_digits: "VE",
    code_3_digits: "VER",
    code_shopify: "VER",
    country_code: "MX",
  },
  {
    name: "Yucatán",
    code_2_digits: "YU",
    code_3_digits: "YUC",
    code_shopify: "YUC",
    country_code: "MX",
  },
  {
    name: "Zacatecas",
    code_2_digits: "ZA",
    code_3_digits: "ZAC",
    code_shopify: "ZAC",
    country_code: "MX",
  },
];
