exports.ORIGIN = {
  name: "Juan Manuel Alvarez",
  company: "",
  email: "jm.alvarezs98@gmail.com",
  phone: "8184642850",
  street: "Rio de la Plata",
  number: "103",
  district: "",
  city: "San Pedro",
  state: "NL",
  category: 1,
  country: "MX",
  postalCode: "66220",
  reference: "",
};
// El Token incluido en el examen arroja el error "Company is not active". Guardé una respuesta dummy de la documentación.
exports.RATES_RESPONSE = {
  meta: "rate",
  data: [
    {
      carrier: "usps",
      service: "priority_cpp",
      serviceDescription: "Usps Priority CPP",
      zone: null,
      deliveryEstimate: "1-3 días",
      deliveryDate: {
        date: "2021-06-07",
        time: "22:00",
        dateDifference: 3,
        timeUnit: "days",
      },
      quantity: 1,
      basePrice: 65.42,
      extendedFare: 0,
      insurance: 0,
      additionalServices: 0,
      totalPrice: 5.42,
      currency: "USD",
      customKey: false,
      importFee: 0,
      taxes: 0,
      cashOnDeliveryCommission: 0,
      cashOnDeliveryAmount: 0,
      customKeyCost: 0,
      smsCost: 0,
      whatsappCost: 0,
      costSummary: [
        {
          quantity: 1,
          basePrice: 5.42,
          extendedFare: 0,
          insurance: 0,
          additionalServices: 0,
          totalPrice: 5.42,
          currency: "USD",
          customKey: false,
          cashOnDeliveryCommission: 0,
          cashOnDeliveryAmount: 0,
          customKeyCommission: 0,
          smsCommission: 0,
          importFee: 0,
          taxes: 0,
          whatsappCommission: 0,
          folio: null,
        },
      ],
    },
    {
      carrier: "usps",
      service: "priority_mail_express_cpp",
      serviceDescription: "Usps Priority Mail Express CPP",
      zone: null,
      deliveryEstimate: "1-2 días",
      deliveryDate: {
        date: "2021-06-04",
        time: "22:00",
        dateDifference: 2,
        timeUnit: "days",
      },
      quantity: 1,
      basePrice: 38.24,
      extendedFare: 0,
      insurance: 0,
      additionalServices: 0,
      totalPrice: 38.24,
      currency: "USD",
      customKey: false,
      importFee: 0,
      taxes: 0,
      cashOnDeliveryCommission: 0,
      cashOnDeliveryAmount: 0,
      customKeyCost: 0,
      smsCost: 0,
      whatsappCost: 0,
      costSummary: [
        {
          quantity: 1,
          basePrice: 38.24,
          extendedFare: 0,
          insurance: 0,
          additionalServices: 0,
          totalPrice: 38.24,
          currency: "USD",
          customKey: false,
          cashOnDeliveryCommission: 0,
          cashOnDeliveryAmount: 0,
          customKeyCommission: 0,
          smsCommission: 0,
          importFee: 0,
          taxes: 0,
          whatsappCommission: 0,
          folio: null,
        },
      ],
    },
    {
      carrier: "usps",
      service: "parcel_select_ground",
      serviceDescription: "Usps Parcel Select Ground",
      zone: null,
      deliveryEstimate: "2-8 días",
      deliveryDate: {
        date: "2021-06-14",
        time: "22:00",
        dateDifference: 8,
        timeUnit: "days",
      },
      quantity: 1,
      basePrice: 6.78,
      extendedFare: 0,
      insurance: 0,
      additionalServices: 0,
      totalPrice: 6.78,
      currency: "USD",
      customKey: false,
      importFee: 0,
      taxes: 0,
      cashOnDeliveryCommission: 0,
      cashOnDeliveryAmount: 0,
      customKeyCost: 0,
      smsCost: 0,
      whatsappCost: 0,
      costSummary: [
        {
          quantity: 1,
          basePrice: 6.78,
          extendedFare: 0,
          insurance: 0,
          additionalServices: 0,
          totalPrice: 6.78,
          currency: "USD",
          customKey: false,
          cashOnDeliveryCommission: 0,
          cashOnDeliveryAmount: 0,
          customKeyCommission: 0,
          smsCommission: 0,
          importFee: 0,
          taxes: 0,
          whatsappCommission: 0,
          folio: null,
        },
      ],
    },
    {
      carrier: "usps",
      service: "priority_mail_cubic",
      serviceDescription: "Usps Priority Mail Cubic",
      zone: null,
      deliveryEstimate: "1-3 días",
      deliveryDate: {
        date: "2021-06-07",
        time: "22:00",
        dateDifference: 3,
        timeUnit: "days",
      },
      quantity: 1,
      basePrice: 9.86,
      extendedFare: 0,
      insurance: 0,
      additionalServices: 0,
      totalPrice: 9.86,
      currency: "USD",
      customKey: false,
      importFee: 0,
      taxes: 0,
      cashOnDeliveryCommission: 0,
      cashOnDeliveryAmount: 0,
      customKeyCost: 0,
      smsCost: 0,
      whatsappCost: 0,
      costSummary: [
        {
          quantity: 1,
          basePrice: 9.86,
          extendedFare: 0,
          insurance: 0,
          additionalServices: 0,
          totalPrice: 9.86,
          currency: "USD",
          customKey: false,
          cashOnDeliveryCommission: 0,
          cashOnDeliveryAmount: 0,
          customKeyCommission: 0,
          smsCommission: 0,
          importFee: 0,
          taxes: 0,
          whatsappCommission: 0,
          folio: null,
        },
      ],
    },
  ],
};

exports.GENERATE_RESPONSE = {
  meta: "generate",
  data: [
    {
      carrier: "ups",
      service: "ground",
      trackingNumber: "1Z68W99A4297214308",
      trackUrl:
        "https://envia.com/rastreo?label=1Z68W99A4297214308&cntry_code=us",
      label:
        "https://s3.us-east-2.amazonaws.com/enviapaqueteria/uploads/ups/1Z68W99A42972143081118461362db7dbe1c.pdf",
      additionalFiles: [],
      totalPrice: 257.12,
      currentBalance: 8230.67,
      currency: "MXN",
    },
  ],
};
